@startuml

legend top
Vista Processos Nível 1 - US001 - As Administrator, I want to create user profiles
end legend

skinparam sequence {
    LifeLineBackgroundColor #lightgrey
}

actor Administrator

activate Administrator

Administrator -> "<<System (C4)>> \n g5 : G5" : 1: Create user profile

activate "<<System (C4)>> \n g5 : G5"

"<<System (C4)>> \n g5 : G5" --> Administrator : 1.1: UI

deactivate "<<System (C4)>> \n g5 : G5"

Administrator -> "<<System (C4)>> \n g5 : G5" : 2: description

activate "<<System (C4)>> \n g5 : G5"

"<<System (C4)>> \n g5 : G5" --> Administrator : 2.1: CREATED/~CREATED

deactivate "<<System (C4)>> \n g5 : G5"

@enduml