@startuml

skinparam sequenceMessageAlign center

legend top
SD US013 Define Scrum Master in Project
end legend

autoactivate on
autonumber 1.1

actor Manager
activate Manager #lightgrey
participant ":DefineScrumMasterUI"
participant ":DefineScrumMasterController"
participant ":Company"
participant "accountContainer\n:AccountContainer"
participant "account:Account"
participant ":AccountMapper"
participant ":ProjectContainer"
participant "project :Project"
participant ":ResourceInProjectContainer"
participant "resourceInProject\n:ResourceInProject"
participant ":RoleContainer"



'list Accounts

Manager -> ":DefineScrumMasterUI" #b: Asks for Accounts
":DefineScrumMasterUI" -> ":DefineScrumMasterController" #b:  getAccountsDTO()
":DefineScrumMasterController" -> ":Company" #b:  getAccounts()
":Company"-->"listAccount :List<Accounts>"** #b: createListAccounts()
":Company"-->":DefineScrumMasterController" #b: listAccounts

":DefineScrumMasterController"->":AccountMapper" #b:listAccountDTO()
":AccountMapper"-->"listAccountsDTO \n:List<AccountsDTO>"** #b: createListAccountsDTO()

loop for each account in listAccounts
":AccountMapper"->"listAccount :List<Accounts>" #b: account=get(i)
deactivate
":AccountMapper"->":AccountMapper" #b: accountDTO=AccountDTO(email, name)
":AccountMapper"-->"accountDTO \n:AccountDTO"** #b: createAccountDTO()
deactivate
":AccountMapper"->"listAccountsDTO \n:List<AccountsDTO>"  #b: addAccountDTO(accountDTO)
deactivate
end

":AccountMapper"-->":DefineScrumMasterController" #b: listAccountsDTO
":DefineScrumMasterController"-->":DefineScrumMasterUI"  #b: listAccountsDTO
":DefineScrumMasterUI" -->Manager  #b: Shows list of accounts

autonumber 2.1
'list projects
autoactivate off
Manager -> ":DefineScrumMasterUI" #b: Asks for list of projects
ref over ":DefineScrumMasterUI"
US015 - As Manager, I want
to get a list of all projects.
end

":DefineScrumMasterUI" -->Manager  #b: Shows list of projects
autoactivate on

'define Scrum master
autonumber 3.1
Manager -> ":DefineScrumMasterUI" #b: Define Scrum Master in Project
":DefineScrumMasterUI" -> ":DefineScrumMasterController" #b: defineRole(email, projectCode, \n allocation, costPerHour,daysFromNow)

":DefineScrumMasterController" -> ":DefineScrumMasterController"  #b: getStartDate(int daysFromNow)
":DefineScrumMasterController" -->"period:Period"** #b: create
deactivate

":DefineScrumMasterController" -> ":Company" #b:  getScrumMasterRole("scrum master")
":Company"-> ":RoleContainer" #b: getScrumMasterRole("scrum master")
":RoleContainer"--> "role:Role"** #b:  create("scrum master")
":RoleContainer"->":RoleContainer" #b: contains(role)
deactivate
":RoleContainer"-->":Company" #b: scrumMasterRole
":Company" --> ":DefineScrumMasterController"  #b: scrumMasterRole


":DefineScrumMasterController" -> "accountContainer\n:AccountContainer" #b:  getAccountByEmail(email)
loop
"accountContainer\n:AccountContainer"->"account:Account"#b: verifyEmail(email)
"accountContainer\n:AccountContainer"<--"account:Account"#b: account
end
"accountContainer\n:AccountContainer"--> ":DefineScrumMasterController" #b: account


":DefineScrumMasterController" ->":ProjectContainer" #b: defineRole(projectCode,account, role\n allocation, costPerHour,period)
":ProjectContainer" ->":ProjectContainer" #b:doesNotExceedPercentageAllocation(account, allocation, LocalDateTime localDateTime)

loop
":ProjectContainer" ->"project :Project" #b:getResourceInProjectContainer()
"project :Project"->":ResourceInProjectContainer"#b:isInProject(account, localDateTime)
loop

":ResourceInProjectContainer"->"resourceInProject\n:ResourceInProject" #b:getAccount().equals(account)
":ResourceInProjectContainer"<--"resourceInProject\n:ResourceInProject" #b:true
end
"project :Project"<--":ResourceInProjectContainer" #b:true
":ProjectContainer" <--"project :Project" #b:true
end
deactivate

":ProjectContainer" ->":ProjectContainer" #b:getProject(projectCode)

loop
":ProjectContainer" ->"project :Project" #b:getProject().equals(projectCode)
":ProjectContainer" <--"project :Project"#b: project
end
deactivate

":ProjectContainer" ->"project :Project"#b:getResourceInProjectContainer()
":ProjectContainer" <--"project :Project"#b:getResourceInProjectContainer

":ProjectContainer" ->":ResourceInProjectContainer"#b:defineRole(String projectCode, Account account,\n Role role, double allocation, double costPerHour,Period period)
":ResourceInProjectContainer"->"resourceInProject\n:ResourceInProject"** #b:create
":ResourceInProjectContainer"->":ResourceInProjectContainer"#b: add(resourceInProject)
deactivate
"project :Project"<--":ResourceInProjectContainer"#b:true
":ProjectContainer" <--"project :Project"#b:true

":DefineScrumMasterController" <--":ProjectContainer" #b:true

":DefineScrumMasterController"-->":DefineScrumMasterUI" #b: true
":DefineScrumMasterUI"-->Manager #b: Scrum Master defined in Project

@enduml