@startuml

legend top
UC US003 - Set Account Profile
end legend

left to right direction
actor "Administrator" as administrator
rectangle System {
  usecase "Set Account Profile" as UC1
}
administrator --> UC1
@enduml
