@startuml
/'Domain Model'/

/'title'/

legend top
Domain Model
end legend

/'Class'/

Object "Profile" as Profile {
-description
}

Object "Account" as Account {
-email
-name
-photo_optional
-phoneNumber
-status
-password
}

Object "Project" as Project {
-code
-name
-description
-startDate
-endDate
-numberSprints
-sprintDuration
-businessSector
-customer
-budget
-typology
}

Object "Report" as Report {
-description
}

Object "ProductBacklog" as ProductBacklog {
}

Object "ResourceInProject" as ResourceInProject {
-startDate
-endDate
-percentageAllocation
-costPerHour
}

Object "Role" as Role{
-roleType
}

Object "Sprint" as Sprint {
-startDate
-endDate
-status
-effort
}

Object "SprintBacklog" as SprintBacklog {
}

Object "Task" as Task {
-typeOfTask
-name
-description
-startDate
-endDate
-percentageExecution
-status
-responsible
-userStory_optional
-hoursSpend
-effortEstimated
}

Object "UserStory" as UserStory {
-userStoryNumber
-actor
-userStoryText
-listOfAcceptanceCriteria
-status
-priority
}

/'Directions'/

Sprint "1" -- "*" UserStory : includes a >
Project "1" -- "*" Sprint : constituted by >
ResourceInProject "*" -- "1" Role : associates to >
ResourceInProject "*" -- "1" Project : allocated to >
Report "*" -- "1" Project : generates a  <
Project "1" -- "1" "ProductBacklog" : includes a >
UserStory "*" - "1" ProductBacklog : decomposed in <
UserStory "1" -- "*" Task : originates a  >
Sprint "1" -- "*" Task : originates a  >
Sprint "1" -- "*" SprintBacklog : includes a  >
SprintBacklog "1" -- "*" UserStory : contains a  >
Account "1" -- "*" ResourceInProject : represents a >
Account "*" - "1" Profile :owns a >

/'notas'/

note right of Profile
    Administrator
    Manager
    User
end note

note left of Report
    Allocations
    KPI
end note

note left of Role
    Project Manager
    Product Owner
    Scrum Master
    Team Member
end note

@enduml