@startuml
/'Domain Model'/

/'title'/

legend top
US012 - Domain Model
end legend

/'Class'/

Object "Profile" as Profile {
-description
}

Object "Account" as Account {
-email
-name
-photo_optional
-phoneNumber
-status
-password
}

Object "Project" as Project {
-code
-name
-description
-startDate
-endDate
-numberSprints
-sprintDuration
-businessSector
-customer
-budget
-typology
}

Object "ProductOwner" as ProductOwner{
-startDate
-endDate
-percentageAllocation
-costPerHour
}

/'Directions'/

ProductOwner "0..1" -- "1" Project : allocated to >
Account "1" -- "1" ProductOwner : represents a >
Account "*" - "1" Profile :owns a >

/'notas'/

note right of Profile
    Administrator
    Manager
    User
end note


@enduml