@startuml

legend top
UC US012 As Manager, I want to define the PO of a project
end legend
left to right direction
actor "Manager"
rectangle System {
    "Manager" --> (Define the Product Owner of a Project)
}

@enduml