@startuml

legend top
SSD US011 Associate a User as Team Member of a Project
end legend

skinparam sequenceMessageAlign center
actor Manager
participant ":System"

Manager -> ":System":  Asks For List Of Accounts
Manager <-- ":System": Shows List of Accounts

Manager -> ":System": Asks For List Of Projects
Manager <-- ":System": Shows List of Projects

Manager -> ":System": Associate Team Member
Manager <-- ":System": Team Member Associated

@enduml